language: python
python:
  - "2.7"

services:
  - docker

before_install:
- docker pull e96tech/consul-server
- docker pull nginx
- docker run -d --net=host e96tech/consul-server -advertise 127.0.0.1 -bootstrap -dc docker -domain test -server
- docker run -d --net=host -v /etc/nginx/conf.d/:/etc/nginx/conf.d/ --name nginx nginx
- docker ps -a
- echo -e '#!/bin/sh\nexec docker exec nginx nginx $@' > "$NGINX_BINARY" && chmod +x "$NGINX_BINARY"
- mkdir $DATA_PATH $NGINX_CONFIG_PATH

env:
 - NGINX_BINARY="$(pwd)/nginx.sh" DATA_PATH="$(pwd)/data" NGINX_CONFIG_PATH="$DATA_PATH/nginx" SECRET=travis

install: "python src/setup.py install"
script: nosetests

