language: python
python:
  - "2.7"

services:
  - docker

before_install:
- docker pull e96tech/consul-server
- docker pull nginx
- docker run -d -p 8500:8500 --name consul e96tech/consul-server -advertise 127.0.0.1 -bootstrap -dc docker -domain test -server
- docker run -d --net=host -v $NGINX_CONFIG_PATH:$NGINX_CONFIG_PATH --name nginx nginx
- docker ps -a
- docker logs consul
- echo -e '#!/bin/sh\nexec docker exec nginx nginx $@' > "$NGINX_BINARY" && chmod +x "$NGINX_BINARY"

env:
 - NGINX_BINARY="$HOME/nginx.sh" DATA_PATH=$HOME NGINX_CONFIG_PATH=$HOME SECRET=travis

install: "python src/setup.py install"
script: nosetests

